# Generated by Django 2.2.1 on 2019-05-21 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=20)),
                ('user_name', models.CharField(blank=True, default=None, max_length=20)),
                ('phone', models.CharField(blank=True, default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('car_no', models.CharField(blank=True, default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=1, unique=True)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path1', models.ForeignKey(blank=True, default=None, limit_choices_to={'target': 'navi'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path1', to='hue.State')),
                ('path2', models.ForeignKey(blank=True, default=None, limit_choices_to={'target': 'navi'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path2', to='hue.State')),
                ('path3', models.ForeignKey(blank=True, default=None, limit_choices_to={'target': 'navi'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path3', to='hue.State')),
                ('path4', models.ForeignKey(blank=True, default=None, limit_choices_to={'target': 'navi'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path4', to='hue.State')),
                ('path5', models.ForeignKey(blank=True, default=None, limit_choices_to={'target': 'navi'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path5', to='hue.State')),
                ('path6', models.ForeignKey(blank=True, default=None, limit_choices_to={'target': 'navi'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path6', to='hue.State')),
                ('path7', models.ForeignKey(blank=True, default=None, limit_choices_to={'target': 'navi'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path7', to='hue.State')),
                ('path8', models.ForeignKey(blank=True, default=None, limit_choices_to={'target': 'navi'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path8', to='hue.State')),
                ('path9', models.ForeignKey(blank=True, default=None, limit_choices_to={'target': 'navi'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path9', to='hue.State')),
                ('room', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='hue.Room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.ForeignKey(default='1', limit_choices_to={'target': 'room'}, on_delete=django.db.models.deletion.CASCADE, to='hue.State', to_field='code'),
        ),
        migrations.AddField(
            model_name='room',
            name='device1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device1', to='hue.Device'),
        ),
        migrations.AddField(
            model_name='room',
            name='device2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device2', to='hue.Device'),
        ),
        migrations.AddField(
            model_name='room',
            name='device3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device3', to='hue.Device'),
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='code',
            field=models.ForeignKey(limit_choices_to={'target': 'device'}, on_delete=django.db.models.deletion.CASCADE, to='hue.State', to_field='code'),
        ),
    ]
