# Generated by Django 2.2.1 on 2019-05-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
