# Generated by Django 2.2.1 on 2019-05-21 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0002_auto_20190521_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.ForeignKey(default='D00', limit_choices_to={'target': 'device'}, on_delete=django.db.models.deletion.CASCADE, to='hue.State', to_field='code'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.ForeignKey(default='R00', limit_choices_to={'target': 'room'}, on_delete=django.db.models.deletion.CASCADE, to='hue.State', to_field='code'),
        ),
    ]
