# Generated by Django 2.2.1 on 2019-07-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0003_auto_20190521_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='user_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
