# Generated by Django 2.2.1 on 2019-07-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0004_auto_20190706_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='checkin_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date_published'),
        ),
    ]
