# Generated by Django 2.2.1 on 2019-07-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0005_room_checkin_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='checkin_date',
            new_name='updated_date',
        ),
    ]
