# Generated by Django 2.2.1 on 2019-07-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0006_auto_20190707_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.IntegerField(default=None)),
                ('carno', models.CharField(default=None, max_length=4)),
                ('reserveOrder', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SignMappingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signid', models.IntegerField(default=None)),
                ('svgdata', models.CharField(default=None, max_length=1000)),
            ],
        ),
    ]
