# Generated by Django 2.2.1 on 2019-08-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0010_auto_20190803_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
