# Generated by Django 2.2.1 on 2019-08-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0012_auto_20190803_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edges',
            old_name='fromSeqId',
            new_name='fromseqid',
        ),
        migrations.RenameField(
            model_name='edges',
            old_name='pId',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='edges',
            old_name='toSeqId',
            new_name='toseqid',
        ),
    ]
