# Generated by Django 2.2.1 on 2019-08-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0013_auto_20190803_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodes',
            old_name='parkId',
            new_name='parkid',
        ),
        migrations.RenameField(
            model_name='nodes',
            old_name='seqId',
            new_name='seqid',
        ),
    ]
