# Generated by Django 2.2.4 on 2019-09-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0014_auto_20190803_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceUuid', models.CharField(max_length=100)),
                ('deviceLng', models.FloatField(default=None)),
                ('deviceLat', models.FloatField(default=None)),
                ('deviceState', models.CharField(max_length=2)),
            ],
        ),
    ]
