# Generated by Django 2.2.4 on 2019-09-18 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0015_emergencypos'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencypos',
            name='callDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
