# Generated by Django 2.2.4 on 2019-11-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hue', '0016_emergencypos_calldate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempHumPm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceUuid', models.CharField(max_length=100)),
                ('deviceLng', models.FloatField(default=None)),
                ('deviceLat', models.FloatField(default=None)),
                ('deviceTempature', models.FloatField(default=None)),
                ('deviceHum', models.FloatField(default=None)),
                ('devicePm', models.FloatField(default=None)),
                ('callDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
